name: Check for l10n updates

on:

  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '24 * * * *'

jobs:
  update-translations:
    runs-on: windows-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Push changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git remote add l10n https://github.com/nvdaaddons/systrayList
        git fetch l10n
        git reset l10n/stable addon/doc addon/locale
        git commit -m "Update translations"
        git pull
        git push
        
            
